### ISSUE TITLE
Icon tags not found

### ISSUE THREAD

**Issue by dest4131** [CodeDaraW/Hacker#10]
Hi,
the computed css rule 
`background: url("../../images/icon-tags.svg") center center no-repeat; `
leads to a 404 error. It should be changed to
`background: url("../images/icon-tags.svg") center center no-repeat;`

Observed with both hexo server and hexo static generated files. I use a blog subfolder, with the following configuration:

`menu:`
`  Home: /blog/`
`  Archives: /blog/archives`
`...`

**Comment by CodeDaraW** [comment]
I haven't tested with your configuration file.  
It seems that you want to put your site in a subdirectory, but you configured the theme's `_config.yml`.  
You'd better configure the global `_config.yml`:
```yml
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://www.demo.com/blog
root: /blog/
```
