### ISSUE TITLE
多说评论添加失败

### ISSUE THREAD

**Issue by Lcrnice** [CodeDaraW/Hacker#2]
添加多说评论后，主页显示有评论按钮，但点击后会404；博客详情内不显示评论框及评论内容

**Comment by CodeDaraW** [comment]
请给出你的主题的`_config.yml`配置文件。  

另外建议不要自己去修改`layout`文件夹中`article.ejs`和`comment.ejs`两个模板文件，模板文件会从配置文件中读取参数，判断是否要使用多说评论和多说评论的用户name。  

主题文件夹中的文件多说配置如下所示：  
```yml
duoshuo: true
duoshuo_name: Your Duoshuo Name
```
请注意，yml文件中k-v对中key后面的冒号应该紧跟一个空格，例如`duoshuo:`后面应该有一个空格

**Comment by Lcrnice** [comment]
我的_config.yml
`menu:
  Home: /
  Archives: /archives

# duoshuo comment
duoshuo: true
duoshuo_name: my_duoshuo_name

# google analytics
googleTrackId: `
直接 clone 的 Hacker 主题，只修改了这两行代码。

**Comment by Lcrnice** [comment]
我的_config.yml
```
menu:
  Home: /
  Archives: /archives

duoshuo: true
duoshuo_name: my_duoshuo_name

googleTrackId: 
```
直接 clone 的 Hacker 主题，只修改了这两行代码。
