### ISSUE TITLE
valine 评论不生效

### ISSUE THREAD

**Issue by Junup** [CodeDaraW/Hacker#42]
```
menu:
  Home: /
  Archives: /archives
  Categories: /categories
  Tags: /tags
# gitment
gitment: false
gitment_owner: 
gitment_repo:
gitment_client_id:
gitment_client_secret: 


# valine comment
valine: true
leancloud_id: EeCn90IlEWXDEFqvbN4ztvvw-********
leancloud_key: GqXMQoJxiDmvJYU5********

# disqus comment
disqus: false
disqus_shortname:

```

这是我的配置项，在Valine安全一项上已经设置我的网址，然而在网站上并没有生效。请问是还不支持吗。还是我忽略了哪些步骤？
