### ISSUE TITLE
配置read_more_btn选项没有任何变化

### ISSUE THREAD

**Issue by sdzbzjh** [CodeDaraW/Hacker#59]
配置read_more_btn选项没有任何变化

_config.yml
```
menu:
  Home: /
  Archives: /archives

# gitment
gitment: false
gitment_owner:
gitment_repo:
gitment_client_id:
gitment_client_secret:

# gitalk
gitalk: false
gitalk_owner:
gitalk_admin: []
gitalk_repo:
gitalk_client_id:
gitalk_client_secret:

# valine comment
valine: false
leancloud_id:
leancloud_key:

# disqus comment
disqus: false
disqus_shortname:

# google analytics
googleTrackId:

# baidu analytics
baiduTrackId:

# whether to show read more button when showing article in excerpt in main page
read_more_btn: true

```
